# Generated by Django 5.1 on 2024-08-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Iranian', 'Iranian Film'), ('Comedy', 'Comedy Theater'), ('Theater', 'Theater'), ('Children', 'Children and Teenagers'), ('Foreign', 'Foreign Film'), ('Art', 'Art and Experience')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
