# Generated by Django 5.1 on 2024-08-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknon', max_length=40),
        ),
    ]
